version: '3.8'
services:
  postgres:
    image: postgres:14
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 10.10.10.2
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
#    ports:
#      - 5432:5432
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
      - POSTGRES_INITDB_ARGS="--auth=scram-sha-256"
###
  element:
    image: vectorim/element-web:latest
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 10.10.10.3
    volumes:
      - ./element-config.json:/app/config.json
###
  synapse:
    image: matrixdotorg/synapse:latest
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 10.10.10.4
    volumes:
      - ./synapse:/data
    ports:
      - "8008:8008"
    depends_on:
      - postgres

#  phpmyadmin:
#    container_name: phpmyadmin
#    image: phpmyadmin
#    restart: always
#    networks:
#      default:
#        ipv4_address: 10.10.10.5
#    ports:
#      - 8090:80
#    environment:
#      - PMA_ARBITRARY=1

networks:
  default:
    external:
      name: matrix_net